### ISSUE TITLE
Connection issues!

### ISSUE THREAD

**Issue by Sharkgamedev** [gordboy/rtl8812au-5.9.3.2#19]
**System:**  
**OS:** Pop! OS 20.10  
**KERNEL:** 5.11  
**DE:** Gnome 3.38  

**Wireless adapter:** https://www.amazon.com/dp/B01CCMUN8C this exact model plugged into USB 2.0 (I believe) port (I can double-check if this is relevant.)  

**Install:**  
Followed instructions in readme to build via dkms.  

**Wireless provider:**  
Comcast, default settings, running on 5GHZ channel.  

**Symptoms:**  
Turn on wifi adapter, available networks come up ok, attempting to connect to the network takes forever, and it starts off with a little question mark in the wifi icon as it can't reach the internet or something, throughout connection I can see in the wifi list it goes from full to nothing and back again at random which leads to some bad experiences, but while it is connected I'm able to do everything I normally would be able to and one time I managed to get a speed test in and it clocked at around 100mbp/s so no issues there except for the very intermittent connection, it was a fluke that I got that in. Shortly thereafter it gives a system notification that activation of wireless connection failed and kicks me off, generally the first time I'm on wifi for a pretty decent time until it kicks me off and then it gets faster and faster after that if I'm able to reconnect in the first place. If I'm reading the wifi logs correctly it's giving error code 6.  

**Other os:**  
On the same exact machine on Windows, this adapter performs beautifully.  

**Also if it helps:**  
This is the lsusb output for it: Bus 001 Device 003: ID 0bda:0811 Realtek Semiconductor Corp. Realtek 8812AU/8821AU 802.11ac WLAN Adapter [USB Wireless Dual-Band Adapter 2.4/5Ghz]
However the realtek chipset appears different in windows, not sure if perhaps this is the issue?  
I also have all power management settings on the wifi adapter disabled.  

**Update:**  
I've actually had a pretty good run recently. Had a little bit of trouble getting off the ground with some weird ``New Access Point/Cell address:Not-Associated`` messages and at one point a ``Set ESSID:"+\x8C\xB6\x87\x1Bd\xF5a\xAB\x1C\xE7\x90[\x90\x1E\xE5\x02\xA8\x11wM\xCD\xE1;\x87`t\x8Av\xDBt\xA1"`` came up. Finally it latched on and was strong, reported 150mb/s with weird pauses where internet my music would pause and I wouldn't be able to load any new websites or random super slow loading despite it still showing full bars where it normally dropped off. Only output from it during this time was ``Scan request completed`` (I had wifi settings open along with the list of visible networks which was triggering constant rescans) Eventually it did fail, not sure if this had anything to do with it but the moment I went to a different tab than the wifi tab in settings it failed with the familiar wireless activation failed message. This was what was logged:
```18:46:47.166555   enxe84e066ccaa6 Scan request completed  
18:46:47.737600   enxe84e066ccaa6 New Access Point/Cell address:Not-Associated  
18:46:47.737628   enxe84e066ccaa6 Set Mode:Managed  
18:46:47.758403   enxe84e066ccaa6 Set Frequency:2.437 GHz (Channel 6)  
18:46:47.758571   enxe84e066ccaa6 Set ESSID:"[Redacted]"  
18:46:47.856568   enxe84e066ccaa6 Scan request completed  
18:46:47.857119   enxe84e066ccaa6 Set Mode:Managed  
18:46:47.867487   enxe84e066ccaa6 Set Frequency:5.785 GHz  
18:46:47.867546   enxe84e066ccaa6 Set ESSID:"[Redacted]"  
18:46:51.836776   enxe84e066ccaa6 New Access Point/Cell address:Not-Associated  
```
(Logs were achieved via: ``iwevent``)

**Comment by gordboy** [comment]
Your device is a 8821 and is not supported by my driver, which only supports 8812.

Try this repo instead

https://github.com/morrownr/8812au

**Comment by Sharkgamedev** [comment]
> Your device is a 8821 and is not supported by my driver, which only supports 8812.
> 
> Try this repo instead
> 
> https://github.com/morrownr/8812au

Thank you! Sorry for wasting your time :(

**Comment by brainstorm** [comment]
> Your device is a 8821 and is not supported by my driver, which only supports 8812.
>
> Try this repo instead
>
> https://github.com/morrownr/8812au

@gordboy I'll give @morrownr repo a try, but your code seems to support 8821A in some capacity?:

```
root@raspberrypi:~# uname -a
Linux raspberrypi 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l GNU/Linux

root@raspberrypi:/usr/src/rtl8812au-5.10.17+# lsusb
Bus 001 Device 004: ID 0bda:0811 Realtek Semiconductor Corp.

root@raspberrypi:/usr/src/rtl8812au-5.10.17+# grep -ri 0811 *
os_dep/linux/usb_intf.c:        {USB_DEVICE(USB_VENDER_ID_REALTEK, 0x0811), .driver_info = RTL8821}, /* Default ID */
```

Would changing the default `Kconfig` to the `RTL8821A` config directive work with your code?:

https://github.com/gordboy/rtl8812au-5.9.3.2/blob/6ef5d8fcdb0b94b7490a9a38353877708fca2cd4/os_dep/linux/usb_intf.c#L194-L211

As in doing something like this, or are there many other changes required that @morrownr repo has and yours does not?:

```diff
diff --git a/Kconfig b/Kconfig
index f87653d..9549647 100644
--- a/Kconfig
+++ b/Kconfig
@@ -1,6 +1,3 @@
-config RTL8812AU
-       tristate "Realtek 8812A USB WiFi"
+config RTL8821A
+       tristate "Realtek 8821A USB WiFi"
        depends on USB
-       ---help---
-         Help message of RTL8812AU
-

```

Or perhaps https://github.com/brektrou/rtl8821CU is the most updated for this particular USB WIFI adapter from EDUP that I have? So confusing :-S

Thanks for putting all this together in any case, super helpful, kudos!

**Comment by brainstorm** [comment]
Uh, scratch that, it turns out that my adapter was a 8811AU variant and it worked perfectly with https://github.com/aircrack-ng/rtl8812au and the [latest RaspberryPI OS released a couple of days ago, so kernel 5.10.17+](https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip).

The most confusing part in all this is that the `lsusb` USB VID:PID does not seem to point to this specific variant in online resources like:

https://linux-hardware.org/index.php?id=usb:0bda-0811

Here are a few teardown photos of the thing to be 100% certain about the IC:

![signal-2021-05-31-224258_001](https://user-images.githubusercontent.com/175587/120265069-897cff80-c2e2-11eb-84c8-af408469f1b4.jpeg)
![signal-2021-05-31-224258_002](https://user-images.githubusercontent.com/175587/120265075-8b46c300-c2e2-11eb-9c20-ae0186757515.jpeg)
![signal-2021-05-31-224258_003](https://user-images.githubusercontent.com/175587/120265079-8d108680-c2e2-11eb-822a-71922c1718ec.jpeg)

Anyway, hope this insight helps somebody struggling with this... or myself in the future forgetting and struggling again XD

**Comment by morrownr** [comment]
Hey Gord,

The link you posted was to the wrong repo. The one he needed is:

https://github.com/morrownr/8821au

@brainstorm 

My driver for the 8811au is more modern than the one at aircrack-ng. You are welcome to come on over. I'll take care of you.

Nick

**Comment by gordboy** [comment]
Hello guys. Sorry for my lack of diligence.

And thanks for taking the time to drop by and keep me straight.

**Comment by brainstorm** [comment]
To both @gordboy and @morrownr I'm fascinated by your great and continued work on those drivers, super kudos to both :D

Now, a question and a wish:

question) @morrownr , when you say that yours is more modern, in a few words (happy if it's deep and technical too), what is the changelog/advantages of your fork over the AirCrack one?

wish) Would you consider .deb packaging directly on your GH fork (via GitHub actions) so that installation on a RPi is just a `dpkg -i rtl8xxx.deb` away? I'd *love* that :)

**Comment by morrownr** [comment]
Gordboy, I like to stop by at times to make sure you haven't gone to sleep. Hey, I'm going to be tied up moving for the next few weeks. It is a long distance move so if you can keep an eye out for any changes we need to make for 5.13 or even 5.14 I would appreciate you giving me a shout.

Nick

**Comment by morrownr** [comment]
@brainstorm 

Quote: "when you say that yours is more modern, in a few words (happy if it's deep and technical too), what is the changelog/advantages of your fork over the AirCrack one?

Reply: I just don't feel like getting deep and technical tonight so... first, mine is not a fork. It is made from clean source. The source code that aircrack-ng driver is based on is several versions older than the version I use. I try to keep the drivers I support at the latest level. What does this have to do with anything? For one thing, Realtek often does their updates for kernel changes a little different than what we might out here in userland. They have full documentation and know what is in the firmware that we can't see so they have an advantage. So, that means the aircrack-ng driver has many more userland updates than my version. That could be good or bad or maybe neither. I'm pretty sure some features have been added but I'd have to do a head to head check and that would take some work. Since the time of the aircrack-ng driver, Realtek is not bundling the driver for the 8812au, 8811au and 8814au in the same package. They are all separate now. My repos consist only of the more modern separate drivers so for your 8811au, you would be getting a driver for that specific chipset, not a driver that also does other chipsets. My 8821au driver is rock solid... but it a Realtek driver so there are limitations.

Quote: "Would you consider .deb packaging directly on your GH fork (via GitHub actions) so that installation on a RPi is just a dpkg -i rtl8xxx.deb away? I'd love that :)"

Reply: There are a lot of creative solutions that come about due to the bad strategy Realtek uses with it USB WiFi support so without going into detail, the answer is no. If you are concerned about having something easy to use on your RasPi, then get one of these adapters: ALFA AWUS036ACM

You can forget compiling drivers or installing .debs. That is an excellent AC1200 adapter that uses a very good in-kernel driver. I use one on my RasPi4b. Take a look at this repo for links to adapters with in-kernel drivers:

https://github.com/morrownr/USB-WiFi

**Comment by gordboy** [comment]
Nick is the real star of this cabaret. And I am happy to stumble along, cherry-picking and pilfering as I go.

**Comment by kimocoder** [comment]
Somebody mentioned aircrack-ng/rtl8812au here?

We'll, haven't had time to do much over there for some time, just maintaing kernel support 👍  sorry for that, maybe I'll find time later..

Anyway, Realtek threw me out from their FTP server, so getting latest sources is harder nowadays, clean sources not vendor based ones.

But, don't forget I've got the RTW88-USB in stock, mac80211 driver!

https://github.com/kimocoder/RTW88-USB

@gordboy 💯
