### ISSUE TITLE
Origin of the driver

### ISSUE THREAD

**Issue by gkalmar** [gordboy/rtl8812au-5.9.3.2#25]
Hi @gordboy,

It is not an issue ticket but rather a question:
Where did you get the source code of the driver?
On the realtek website I only found a quite outdated windows driver.

**Comment by gordboy** [comment]
I was gifted the driver by an anonymous source. It seems to be a legit in-house Realtek driver.

Previously, we were able to access the Realtek FTP site, but this is no longer available.

My guess is that a friendly Realtek dev has given the community this source. The code is GPL 2 so it is not like it is proprietary or anything.

I hope that answers your question.

**Comment by gordboy** [comment]
You might find this useful -

https://github.com/morrownr/USB-WiFi

**Comment by yichangshengwu** [comment]
i got a similar copy at Tenda U12 download page,
https://www.tenda.com.cn/product/download/U12.html

![截图_2021-09-04_06-55-56](https://user-images.githubusercontent.com/43059917/132072485-212b1d3d-819c-4cca-9d94-15d81619fe0c.png)

**Comment by gordboy** [comment]
@yichangshengwu that driver is 5 years old, which is an eternity in the Realtek world.

Now see, the thing about Realtek is that you have to keep patching the code every time an API change occurs. The best way is to get a new version from Realtek and that means you have less patching to do.

We are just about at the point where I am considering dropping support for this driver, due to USB issues with kernel 5.13.

**Comment by gordboy** [comment]
Not maintaining this repo any further. There are better devices and drivers.
