### ISSUE TITLE
non-UNIX line endings

### ISSUE THREAD

**Issue by morrownr** [gordboy/rtl8812au-5.9.3.2#4]
gordboy,

Would you mind sharing how you search the code for non-Unix line endings?

**Comment by gordboy** [comment]
There is a command called `fromdos` which converts text files from DOS endings to UNIX endings. It is included in the `tofrodos` package in Debian and derivatives. I use it in a script run from the top level of the source, that finds every regular source text file and runs the `fromdos` command on it:

```
find . -type f -not -iwholename '*.git*' -exec fromdos {} +
```
Notice how this is careful not to clobber any GIT stuff. And it is pretty quick. Run and forget.

As for the trailing whitespace, again I use a script but this time with `sed` command:

```
find . -type f -not -iwholename '*.git*' -exec sed --in-place 's/[[:space:]]\+$//' {} +
```

What this one does is replace anything that `sed` thinks is any combination of whitespace at the end of a line, with the empty string, using the internal `sed` command `s/OLD/NEW/`.

Again careful with any GIT stuff. Again pretty quick. Run and forget.

I suppose the purist might prefer something like:

```
find . -not -path "./.git*" -type f -exec SOMETHING ...
```

or even the horrible (but correct in some sense)

```
find . -path "./.git" -prune -false -o -type f -exec SOMETHING ...
```

And obviously (this being GNU/Linux) you can use things like `awk` or `tr` instead of, or as well as `sed`, or even use `sed` exclusively instead of `fromdos`. The possibilities are endless, but time-consuming ...

Any which way, you have to be careful not to clobber files in the hidden `git` tree. All my work is done in Linux, using `vim` and I try hard not to add to the badness with my own edits.

**Comment by gordboy** [comment]
See here for a lengthy discussion on this whole business of excluding things from a `find` command

https://stackoverflow.com/questions/4210042/how-to-exclude-a-directory-in-find-command

My code is not the fastest, nor the purest, but is easily read and understood.

There are only 570+ files in the source tree anyway, so the little trick with `{} +` at the end of the `find` command, instead of `{} \;` works nicely also, since both `sed` and `fromdos` accept multiple files in their respective arguments lists.
