### ISSUE TITLE
Not working on Linux 5.10.4-arch2-1 and 5.4.86-1-lts on Endeavour OS

### ISSUE THREAD

**Issue by Azimoth** [gordboy/rtl8812au-5.9.3.2#8]
Hi,
I have an Edimax Wi-Fi AC600 Adapter (7392:b611), which I could use with rtl8812au-5.4.6.2 up until Linux 5.10.3 on Endeavour OS. (I only needed to replace a811 with b611 in usb_intf.c) By now the kernel was upgraded to said 5.10.4-arch2-1, but still the wifi adapter is not working. 

For some reason it stopped working at this point and even upgrading to rtl8812au-5.9.3.2 didn't help. At the same time, the LTS kernel of Endeavour OS was updated to 5.4.86-1-lts and here both versions don't work anymore as well.

How could I narrrow down the problem? I browsed through journalctl but didn't find anything that I would consider connected to this problem (which doesn't mean much)
Could you point me in the right direction?

**Comment by gordboy** [comment]
The problem is that your chipset is not 8812AU, it is 8821AU or perhaps even 8811AU. It says very clearly right at the top of the repo README that only 8812AU is supported.

Anyways, if it was working under 5.6.4.2, it was by sheer accident. Another thing, you should add a new line to the source, instead of changing an existing one. And another thing, you should tell the maintainer so they can add it for other users ...

As to a fix, well I have no plans to change this driver, but you might have better luck with these drivers which say they have added various extra support, or had it to start with

https://github.com/kimocoder/rtl8812au-5.9.3.2

https://github.com/morrownr/8821au

Hope that helps.

**Comment by Azimoth** [comment]
That's a fairly convincing reason why it doesn't work. 8821AU it is. Lucky me it worked so far, I guess.^^

The version provided by morrownr worked out of the box. 

Thx for the hint! And for answering so quickly!
